export const termsHeaderData = {
title:`TERMOS E CONDIÇÕES GERAIS DE USO - CHEERSCLUB`,
subTitle:
`
*Serviço destinado exclusivamente para maiores de 18 anos.
* Leia atentamente todos os termos e condições abaixo. Ao iniciar o uso do serviço, você estará concordando com todos os termos e condições.
* Última atualização em 10 de fevereiro de 2022.`, 
introduction:
`
ESTE E UM CONTRATO FIRMADO POR VOCÊ, DENOMINADO DE AGORA EM DIANTE COMO USUÁRIO E A CHEERS, EMPRESA CADASTRADA NO CNPJ SOB O Nº 45.285.622/0001-41 COM SEDE EM FERNÃO DIAS, 251 PINHEIROS – CEP:
054.270.10, DE AGORA EM DIANTE DENOMINADA SIMPLESMENTE DE CHEERS. ESTES TERMOS E CONDIÇÕES DE USO REGEM TODOS OS SERVIÇOS DISPONIBILIZADOS PELA CHEERS, SEJAM PARA DISPOSITIVOS MÓVEIS (ANDROID, IOS, WINDOWS MOBILE OU SEMELHANTES), SERVIDORES, COMPUTADORES PESSOAIS OU SERVIÇOS DE WEB (REDE MUNDIAL DE COMUTADORES).`, 
};


export const termsOfUseData = [
    //page 1 
{
idPage:1, 
p1Title:`1. DA ACEITAÇÃO`, 
p1:`
1.1  SEJA BEM-VINDO AO CHEERS, O MELHOR CLUBE DE DRINKS DO BRASIL. LEIA ATENTAMENTE TODOS OS TERMOS E CONDIÇÕES GERAIS DE USO AQUI APRESENTADOS.
AO INICIAR O USO DO APLICATIVO/SERVIÇO ONLINE (CLICANDO NO CAMPO “LI E ACEITO”), VOCÊ ESTARÁ CONCORDANDO DE FORMA LIVRE E EXPRESSA COM TODAS AS CONDIÇÕES DE USO AQUI ESTABELECIDAS. 
LEIA COM ATENÇÃO. AGORA É SÓ FAZER PARTE DO NOSSO CLUBE.

`,
p2Title:`2 . DA RESTRIÇÃO DE IDADE`, 
p2:`
2.1 OS SERVIÇOS DISPONIBILIZADOS PELA CHEERS, SEJA PELO APLICATIVO OU SITE, DESTINAM-SE EXCLUSIVAMENTE PARA MAIORES DE 18 ANOS DE IDADE.

`,
p3Title:`3. DO OBJETO`, 
p3:`
3.1 O CHEERS SURGIU COM O OBJETIVO DE PROMOVER UMA EXPERIÊNCIA ÚNICA NO MERCADO DE BARES E RESTAURANTES, PROMOVENDO AO USUÁRIO UMA ALTERNATIVA AO CONSUMO TRADICIONAL DE BEBIDAS DIVERSAS, FUGINDO DO PADRÃO.

`,
},
//page2
{
idPage:2,
p1:`3.2 A FINALIDADE DO CHEERS É INTERMEDIAR O CONSUMO DE BEBIDAS, OFERECENDO AO USUÁRIO ATRAVÉS DE UMA ASSINATURA (SEMANAL, MENSAL OU ANUAL) UMA VARIEDADE DE BEBIDAS DENTRO DE UMA REDE DE PARCEIROS (BARES, RESTAURANTES E DEMAIS LOCAIS CONVENIADOS), POSSIBILITANDO UMA DEGUSTAÇÃO DAS MELHORES BEBIDAS E DESCOBRINDO OS MELHORES
LUGARES PARA SE BRINDAR.

`,
p2Title:`4. DOS DADOS FORNECIDOS`, 
p2:`
4.1 O CHEERS PODERÁ UTILIZAR INFORMAÇÕES DOS USUÁRIOS (DADOS COLETADOS),SENDO PERMITIDO O USO, ARMAZENAMENTO, PROCESSAMENTO, TRANSMISSÃO OU DISPONIBILIZAÇÃO A TERCEIROS COM
FINALIDADE EXCLUSIVA DA PRESTAÇÃO DOS SERVIÇOS FORNECIDOS.

4.2 O CHEERS SE COMPROMETE A ADOTAR MEDIDAS DE SEGURANÇA, TÉCNICAS E ADMINISTRATIVAS, QUE VISEM A PROTEÇÃO DE TODOS OS DADOS COLETADOS DOS USUÁRIOS ATRAVÉS DE SEU APLICATIVO, SITE OU DE
QUALQUER OUTRA FORMA DE FORNECIMENTO.

4.3 O CHEERS PODERÁ SOLICITAR AOS USUÁRIOS, AINDA QUE DE FORMA PERIÓDICA, INFORMAÇÕES COMPLEMENTARES QUE ENTENDER NECESSÁRIA À PRESTAÇÃO DOS SERVIÇOS.

4.4 O CHEERS PODERÁ MANTER E UTILIZAR OS DADOS PESSOAIS DOS USUÁRIOS, AINDA QUE SENSÍVEIS, APENAS PARA FORNECER MELHORES SERVIÇOS, DE FORMA INDIVIDUALIZADA OU GERAL, DURANTE TODO O
PERÍODO CONTRATADO, RESPEITANDO AS FINALIDADES CONTRATUAIS E, MESMO APÓS O TÉRMINO DA CONTRATAÇÃO, PARA CUMPRIMENTO DE OBRIGAÇÃO LEGAL NOS TERMOS DA LEI 13.709/2018.

4.5 O CHEERS PODERÁ COLETAR OS DADOS DOS USUÁRIOS POR MEIO DE TECNOLOGIA DE ARMAZENAMENTO LOCAL, POR MEIO DA UTILIZAÇÃO DE COOKIES OU TECNOLOGIAS SIMILARES OU DEVIDAMENTE REGULAMENTADAS,
POSSIBILITANDO A CORRETA IDENTIFICAÇÃO DO USUÁRIO E USO CORRETO REFERENTE AOS DADOS COLETADOS.

`, 
p3Title:`4. DA PROPRIEDADE INTELECTUAL`, 
p3:
`4.1 AO UTILIZAR OS SERVIÇOS DO CHEERS, O USUÁRIO CONCORDA EM RESPEITAR TODOS OS TERMOS DA POLÍTICA DE PRIVACIDADE.

4.2 O APLICATIVO, SITE, BEM COMO TODO CONTEÚDO EXPOSTO NA PLATAFORMA, É DE INTEIRA PRORIEDADE DO CHEERS, SENDO VEDADA SUA`,
},
//page3 
{
idPage:3,
p1:
`CÓPIA, REPRODUÇÃO, REPRESENTAÇÃO, ADAPTAÇÃO, ALTERAÇÃO DE QUALQUER FORMA OU POR QUALQUER MEIO E FINALIDADE, AINDA QUE DE FORMA PARCIAL, SEM AUTORIZAÇÃO PRÉVIA E EXPRESSA DO CHEERS.
4.3 O USO DO APLICATIVO, SITE OU QUALQUER OUTRO SERVIÇO FORNECIDO PELO CHEERS, SEJA POR QUALQUER MEIO OU FORMA, NÃO CONCEDE AO USUÁRIO QUALQUER DIREITO DE PROPRIEDADE INTELECTUAL AOS ELEMENTOS
EXISTENTES.

`,
p2Title:`5. DAS OBRIGAÇÕES`, 
p2:`
5.1 O CHEERS SE COMPROMETE A OFERTAR AO USUÁRIO O SERVIÇO CONTRATADO, PREZANDO PELA MELHORIA E BEM-ESTAR NO USO DE SUAS PLATAFORMAS.

5.2 O CHEERS DISPONIBILIZARÁ EM SUAS PLATAFORMAS VIRTUAIS ESPAÇO DESTINADO AO USUÁRIO DEVIDAMENTE CADASTRADO QUE, CONFORME O PLANO ADQUIRIDO, POSSA ESCOLHER BARES E RESTAURANTES PARCEIROS
PARA CONSUMO DE BEBIDAS, DISPONIBILIZANDO OS PARCEIROS DE FORMA ATUALIZADA, POSSIBILITANDO A MELHOR EXPERIÊNCIA.

5.3 O CHEERS SE COMPROMETE, POR MEIO DE ARMAZENAMENTO EM
SERVIDORES OU QUALQUER OUTRO MEIO ELETRÔNICO DE SEGURANÇA, A
CONFIDENCIALIDADE DAS INFORMAÇÕES FORNECIDAS, SENDO UTILIZADAS
APENAS COM OBJETIVO DA PRESTAÇÃO DOS SERVIÇOS FORNECIDOS.

5.4 O USUÁRIO, APÓS CADASTRAMENTO EFETUADO NO APLICATIVO OU SITE, SE COMPROMETE A NÃO DIVULGAR LOGIN E SENHA DE ACESSO, NEM PERMITIR O USO DAS INFORMAÇÕES POR TERCEIROS, RESPONSABILIZANDO-
SE PELAS CONSEQUÊNCIAS LEGAIS DAS INFORMAÇÕES PESSOAIS.

5.5 CABERÁ AO USUÁRIO FORNECER INFORMAÇÕES CADASTRAIS TOTALMENTE VERÍDICAS E EXATAS, RESPONSABILIZANDO-SE PELOS DADOS FORNECIDOS, INCLUSIVE EM TODAS AS SEARAS JURÍDICAS.

5.6 CABERÁ AINDA AO USUÁRIO O EFETIVO PAGAMENTO REFERENTE AOS SERVIÇOS CONTRATADOS, SENDO REALIZADA POR QUALQUER FORMA DISPONIBILIZADA NAS PLATAFORMAS OFERECIDAS PELO CHEERS.

`
},
//page4
{
idPage:4,
p1Title:`6. ATUALIZAÇÃO DO TERMO`, 
p1:`
O PRESENTE TERMO DE USO PODERÁ TER SEU CONTEÚDO ALTERADO, EM TODO OU EM PARTE, A QUALQUER TEMPO POR PARTE CHEERS PARA ADEQUAÇÕES E INSERÇÕES,OBJETIVANDO O APRIMORAMENTO DOS SERVIÇOS DISPONIBILIZADOS. 
SALVO DISPOSIÇÃO LEGAL, O USUÁRIO SERÁ NOTIFICADO PARA ANALISAR OS NOVOS TERMOS DE USO, PODENDO CONTINUAR UTILIZANDO OS SERVIÇOS FORNECIDOS OU PROMOVENDO O CANCELAMENTO DA CONTA.

`,
}
];

